### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#134]
```

13:49:52.896 [main] ERROR io.gomint.server.Bootstrap - GoMint crashed:
 java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:100) [GoMint.jar:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907) ~[?:1.8.0_151]
        at java.util.ArrayList$Itr.next(ArrayList.java:857) ~[?:1.8.0_151]
        at io.gomint.server.world.WorldManager.update(WorldManager.java:52) ~[GoMint.jar:?]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:312) ~[GoMint.jar:?]
        ... 5 more
GoMint>

```

**Comment by Janmm14** [comment]
Passiert das auch ohne Plugins? Oder passiert das, wenn ein Plugin irgendwas bestmmtes macht?

**Comment by Goodstuff4UonYT** [comment]
Ist passiert, als ein Plugin eine Welt entladen hat, die Entities dort despawnt hat, und dann eine neue Welt geladen hat, komischerweise ist das Problem nicht immer wieder aufgetreten, sondern bis jetzt nur einmal.

**Comment by Goodstuff4UonYT** [comment]
```
21:24:19.792 [main] ERROR io.gomint.server.Bootstrap - GoMint crashed:
 java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:100) [GoMint.jar:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907) ~[?:1.8.0_151]
        at java.util.ArrayList$Itr.next(ArrayList.java:857) ~[?:1.8.0_151]
        at io.gomint.server.world.WorldManager.update(WorldManager.java:52) ~[GoMint.jar:?]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:316) ~[GoMint.jar:?]
        ... 5 more

```

**Comment by Janmm14** [comment]
Das CME's nicht immer auftreten ist nichts neues. Wenn du irgendwie asynchron mit der Welt interagierst, probier es stattdessen auf synchon zu ändern, also auf dem Main-Thread.
