### ISSUE TITLE
npe -crafting

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#159]
```
08:06:13.040 [main] ERROR io.gomint.server.network.PlayerConnection - Error whilst processing packet:
 java.lang.NullPointerException: null
        at io.gomint.server.network.handler.PacketCraftingEventHandler.handle(PacketCraftingEventHandler.java:57) ~[GoMint.jar:?]
        at io.gomint.server.network.handler.PacketCraftingEventHandler.handle(PacketCraftingEventHandler.java:18) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handlePacket(PlayerConnection.java:553) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handleBufferData(PlayerConnection.java:502) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:432) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.updateNetwork(PlayerConnection.java:304) [GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:210) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager$1.accept(NetworkManager.java:75) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager$1.accept(NetworkManager.java:72) [GoMint.jar:?]
        at io.gomint.server.util.collection.KolobokePlayerConnectionMap.forEach(KolobokePlayerConnectionMap.java:179) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:197) [GoMint.jar:?]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:310) [GoMint.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:
```

**Comment by geNAZt** [comment]
What do you craft?

**Comment by Goodstuff4UonYT** [comment]
@geNAZt workbench
