### ISSUE TITLE
BlockWallSign is broken (getLine)

### ISSUE THREAD

**Issue by EinBexiii** [gomint/gomint#177]
08:53:41.569 [GoMint Thread #5] WARN  net.bexania.signsystem.main.Main - A task thrown a Exception
 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_161]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_161]
        at io.gomint.server.world.block.WallSign.getLine(WallSign.java:96) ~[GoMint.jar:?]
        at net.bexania.signsystem.task.qbw.QbwCheckStatus$1$1.accept(QbwCheckStatus.java:22) ~[?:?]
        at net.bexania.signsystem.task.qbw.QbwCheckStatus$1$1.accept(QbwCheckStatus.java:18) ~[?:?]
        at io.gomint.server.world.WorldAdapter.lambda$iterateBlocks$6(WorldAdapter.java:1287) ~[GoMint.jar:?]
        at io.gomint.server.world.ChunkCache.iterateAll(ChunkCache.java:275) ~[GoMint.jar:?]
        at io.gomint.server.world.WorldAdapter.iterateBlocks(WorldAdapter.java:1277) ~[GoMint.jar:?]
        at net.bexania.signsystem.task.qbw.QbwCheckStatus$1.run(QbwCheckStatus.java:18) ~[?:?]
        at io.gomint.server.scheduler.AsyncScheduledTask.run(AsyncScheduledTask.java:91) [GoMint.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Code:

if(blockWallSign.getLine(1).equalsIgnoreCase("Test")){
                                // Code
}

**Comment by geNAZt** [comment]
Fixed
