### ISSUE TITLE
1.2.3 Bugs

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#187]
## Bugs without ProxProx
- [ ] GUIs are opening multiple times
- [x] Nametag is broken
- [x] Ghast Sound is not working
- [x] LEVELUP Sound is not working
- [x] Chunks not Loading after teleport to another world (I see the old world) Only win 10
- [x] Noteblock sounds are not working
- [x] ~~Modal Form is not working (1)~~
- [x] NPE (2)

## Bugs with ProxProx
- [x] Cannot join

## Attachments

(2)
`
 java.lang.Exception: null
        at io.gomint.server.world.BlockRuntimeIDs.fromLegacy(BlockRuntimeIDs.java:58) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldAdapter.appendUpdatePackets(WorldAdapter.java:827) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:284) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:189) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:385) [GoMint.jar:1.0.0-SNAPSHOT]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_151]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:97) [GoMint.jar:1.0.0-SNAPSHOT]
08:35:19.681 [main] ERROR io.gomint.server.Bootstrap - GoMint crashed:
 java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:97) [GoMint.jar:1.0.0-SNAPSHOT]
Caused by: java.lang.NullPointerException
        at io.gomint.server.world.WorldAdapter.appendUpdatePackets(WorldAdapter.java:827) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:284) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:189) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:385) ~[GoMint.jar:1.0.0-SNAPSHOT]
        ... 5 more
GoMint>
`

**Comment by geNAZt** [comment]
" GUIs are opening multiple times"

```java

    @EventHandler
    public void onEntityTeleport( EntityTeleportEvent event ) {
        if ( event.getEntity() instanceof EntityPlayer ) {
           // ( (EntityPlayer) event.getEntity() ).getInventory().clear();
            CustomForm form = GoMint.instance().createCustomForm( "Teleport Feedback" );
            form.addToggle( "success", "Waren Sie mit dem Teleport zufrieden?", false );
            ( (EntityPlayer) event.getEntity() ).showForm( form );
        }


    }
```

Opens exactly once after a teleport like i would assume. Please describe the issue further

**Comment by geNAZt** [comment]
"Modal form is not working"

```java
Modal form = GoMint.instance().createModal( "Teleport Feedback", "Waren Sie mit dem Teleport zufrieden?" );
            form.setTrueButtonText( "Yay" );
            form.setFalseButtonText( "Ney" );
            ( (EntityPlayer) event.getEntity() ).showForm( form );
```

resulting in: https://i.imgur.com/sG4p7Ey.png

**Comment by geNAZt** [comment]
"Chunks not Loading after teleport to another world (I see the old world) Only win 10"

Please provide both worlds and the coords you teleport to

**Comment by geNAZt** [comment]
For your (2) i need the full log, there is a message before the exception i need that

**Comment by Goodstuff4UonYT** [comment]
@geNAZt for 2:
```
16:17:59.017 [main] WARN  io.gomint.server.world.BlockRuntimeIDs - Unknown blockId and dataValue combination: 0:2
 java.lang.Exception: null
        at io.gomint.server.world.BlockRuntimeIDs.fromLegacy(BlockRuntimeIDs.java:58) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldAdapter.appendUpdatePackets(WorldAdapter.java:827) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:284) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:189) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:385) [GoMint.jar:1.0.0-SNAPSHOT]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_151]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:96) [GoMint.jar:1.0.0-SNAPSHOT]
16:17:59.019 [main] INFO  io.gomint.server.world.BlockRuntimeIDs - Got palette id null for 0:2
16:17:59.019 [main] ERROR io.gomint.server.Bootstrap - GoMint crashed:
 java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:96) [GoMint.jar:1.0.0-SNAPSHOT]
Caused by: java.lang.NullPointerException
        at io.gomint.server.world.WorldAdapter.appendUpdatePackets(WorldAdapter.java:827) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:284) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:189) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:385) ~[GoMint.jar:1.0.0-SNAPSHOT]
        ... 5 more
GoMint> [MySQL] Die Verbindung zur MySQL wurde Erfolgreich beendet!

```

**Comment by geNAZt** [comment]
NPE fixed

**Comment by geNAZt** [comment]
Since there was no answer on the gui open multiple times and i can't reproduce it with said code i close this issue. Please reopen if needed
