### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#243]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:

[main] ERROR io.gomint.server.network.PlayerConnection - Error whilst processing packet:
 java.lang.IllegalArgumentException: Cannot read more bytes than are available
        at io.gomint.jraknet.PacketBuffer.ensureRemaining(PacketBuffer.java:73) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.jraknet.PacketBuffer.readInt(PacketBuffer.java:96) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.packet.PacketPlayState.deserialize(PacketPlayState.java:36) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handleBufferData(PlayerConnection.java:510) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:442) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.updateNetwork(PlayerConnection.java:339) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:225) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:190) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:416) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:226) [GoMint.jar:1.0.0-SNAPSHOT]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_171]

**Comment by LucGamesYT** [comment]
MoleCraft-1 Log nach dem der Spieler in eine andere Welt teleportiert wird
[latest.log](https://github.com/GoMint/GoMint/files/2042649/latest.log)

**Comment by LucGamesYT** [comment]
Lobby-1 Log nach dem der Spieler wieder auf die Lobby transfert wird nach dem der Server geschlosen wurde
[latest.log](https://github.com/GoMint/GoMint/files/2042650/latest.log)

**Comment by LucGamesYT** [comment]
03:51:27.714 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:27.764 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:27.814 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:27.864 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=LOGIN_SUCCESS)
03:51:27.865 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:27.914 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:27.965 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:28.015 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:28.065 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:28.115 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=LOGIN_SUCCESS)
03:51:28.115 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:28.165 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:28.215 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:28.265 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
03:51:28.315 [main] WARN  io.gomint.server.network.PlayerConnection - No handler for PacketPlayState(state=null)
