### ISSUE TITLE
io.gomint.server.world.anvil.AnvilChunkAdapter - Error whilst parsing chunk nbt: 

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [gomint/gomint#248]
```
2018-06-03 18:21:15.103 [main] ERROR io.gomint.server.world.anvil.AnvilChunkAdapter - Error whilst parsing chunk nbt: 
java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END
	at java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:992) ~[?:1.8.0_131]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:572) ~[?:1.8.0_131]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:802) ~[?:1.8.0_131]
	at io.gomint.taglib.StringUtil.fromUTF8Bytes(StringUtil.java:26) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.taglib.NBTStreamReader.readStringValue(NBTStreamReader.java:59) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.taglib.NBTStream.readTagCompoundValue(NBTStream.java:70) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.taglib.NBTStream.readTagListValue(NBTStream.java:295) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.taglib.NBTStream.readTagCompoundValue(NBTStream.java:144) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.taglib.NBTStream.readTagCompoundValue(NBTStream.java:152) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.taglib.NBTStream.parse(NBTStream.java:55) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.anvil.AnvilChunkAdapter.loadFromNBT(AnvilChunkAdapter.java:224) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.anvil.RegionFile.loadChunk(RegionFile.java:172) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.anvil.AnvilWorldAdapter.loadChunk(AnvilWorldAdapter.java:478) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.entity.Entity.getChunk(Entity.java:868) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.EntityManager.spawnEntityAt(EntityManager.java:341) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.WorldAdapter.spawnEntityAt(WorldAdapter.java:508) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.entity.EntityPlayer.teleport(EntityPlayer.java:408) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.entity.Entity.teleport(Entity.java:1156) [GoMint.jar:1.0.0-SNAPSHOT]
	at net.multilabs.gomint.bedwars.tasks.BedwarsTask.teleportiereSpieler(BedwarsTask.java:764) [bedwars-0.0.1-SNAPSHOT.jar:?]
	at net.multilabs.gomint.bedwars.tasks.BedwarsTask.run(BedwarsTask.java:230) [bedwars-0.0.1-SNAPSHOT.jar:?]
	at io.gomint.server.scheduler.SyncScheduledTask.run(SyncScheduledTask.java:57) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.scheduler.SyncTaskManager.update(SyncTaskManager.java:81) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:418) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.GoMintServer.<init>(GoMintServer.java:226) [GoMint.jar:1.0.0-SNAPSHOT]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_131]
	at io.gomint.server.Bootstrap.main(Bootstrap.java:107) [GoMint.jar:1.0.0-SNAPSHOT]
```

**Comment by geNAZt** [comment]
Please send me the corrupted world in Discord

**Comment by geNAZt** [comment]
World loads fine for me on latest gomint. Can't reproduce

**Comment by Goodstuff4UonYT** [comment]
@geNAZt it only occurs sometimes while teleporting the player into the world

**Comment by geNAZt** [comment]
Code, Coordinates? I loded the complete world into gomint and i got no loading error
