### ISSUE TITLE
Sample world 

### ISSUE THREAD

**Issue by markusstephanides** [gomint/gomint#3]
Since I can't get any anvil world to load with GoMint, is there a sample map you use to test GoMint that you could provide a download link for?

**Comment by cieldeville** [comment]
Please provide us with further details on what committed version you are using, how you built GoMint, if it is throwing any exception or displays any other errors. Oddly enough, we have encountered chunk related issues during testing but all anvil worlds loaded correctly.

**Comment by markusstephanides** [comment]
I'm using the latest commit and I build GoMint using _mvn clean install_

This is the exception that I'm getting:

```
java.io.IOException: Failed to load / generate chunk surrounding spawn region
at io.gomint.server.world.anvil.AnvilWorldAdapter.prepareSpawnRegion(AnvilWorldAdapter.java:400) ~[classes/:?]
at io.gomint.server.world.anvil.AnvilWorldAdapter.load(AnvilWorldAdapter.java:515) ~[classes/:?]
at io.gomint.server.world.WorldManager.loadAnvilWorld(WorldManager.java:122) ~[classes/:?]
at io.gomint.server.world.WorldManager.loadWorld(WorldManager.java:107) ~[classes/:?]
at io.gomint.server.GoMintServer.<init>(GoMintServer.java:152) [classes/:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_60]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_60]
at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_60]
at io.gomint.server.Bootstrap.main(Bootstrap.java:78) [classes/:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:?]
```

**Comment by geNAZt** [comment]
This happens when the spawn region has not been generated. Currently gomint has no generators so it fails to load. Just use a world which has been generated with the pc edition.

**Comment by Digot** [comment]
I have generated a world using a different PE server and it throws that error:

    java.io.IOException: Failed to load / generate chunk surrounding spawn region
	at io.gomint.server.world.anvil.AnvilWorldAdapter.prepareSpawnRegion(AnvilWorldAdapter.java:400) ~[classes/:?]
	at io.gomint.server.world.anvil.AnvilWorldAdapter.load(AnvilWorldAdapter.java:515) ~[classes/:?]
	at io.gomint.server.world.WorldManager.loadAnvilWorld(WorldManager.java:122) ~[classes/:?]
	at io.gomint.server.world.WorldManager.loadWorld(WorldManager.java:107) ~[classes/:?]
	at io.gomint.server.GoMintServer.<init>(GoMintServer.java:152) [classes/:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_40]
	at io.gomint.server.Bootstrap.main(Bootstrap.java:78) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
