### ISSUE TITLE
If you drink milk while you're in water

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#313]
```
 java.lang.NullPointerException: null
        at io.gomint.server.world.block.Blocks.replaceWithItem(Blocks.java:102) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldAdapter.useItemOn(WorldAdapter.java:1102) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.handler.PacketInventoryTransactionHandler.handleUseItem(PacketInventoryTransactionHandler.java:216) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.handler.PacketInventoryTransactionHandler.handle(PacketInventoryTransactionHandler.java:91) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.handler.PacketInventoryTransactionHandler.handle(PacketInventoryTransactionHandler.java:36) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handlePacket(PlayerConnection.java:643) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handleBufferData(PlayerConnection.java:588) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:511) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.updateNetwork(PlayerConnection.java:420) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:293) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:190) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:453) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:245) [GoMint.jar:1.0.0-SNAPSHOT]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_171]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:92) [GoMint.jar:1.0.0-SNAPSHOT]
```

**Comment by ghost** [comment]
I consumed milk under water. Nothing suspicious happened. Maybe just a random incident?

**Comment by ghost** [comment]
Is this still up to date?

**Comment by ghost** [comment]
Closed due to no response.
