### ISSUE TITLE
Error when interacting with items

### ISSUE THREAD

**Issue by LucGamesYT** [gomint/gomint#426]
**Describe the bug**
When I break or interact with something then I get an error printed in the console 

**To Reproduce**
Might not be reproducible.

**Expected behavior**
No error in the console.

**Screenshots**
Got a hastebin instead
https://pastebin.com/pVrRuQQw

```
2018-11-18 12:15:18.409 [main] ERROR io.gomint.server.network.PlayerConnection - Could not deserialize / handle packet
java.lang.NullPointerException: null
	at io.gomint.server.network.handler.PacketInventoryTransactionHandler.handleUseItem(PacketInventoryTransactionHandler.java:245) ~[gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.network.handler.PacketInventoryTransactionHandler.handle(PacketInventoryTransactionHandler.java:93) ~[gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.network.handler.PacketInventoryTransactionHandler.handle(PacketInventoryTransactionHandler.java:35) ~[gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.network.PlayerConnection.handlePacket(PlayerConnection.java:717) ~[gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.network.PlayerConnection.handleBufferData(PlayerConnection.java:658) [gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:571) [gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.network.PlayerConnection.updateNetwork(PlayerConnection.java:460) [gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:316) [gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.network.NetworkManager.update(NetworkManager.java:213) [gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:495) [gomint-1542058442637.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.Bootstrap.main(Bootstrap.java:117) [gomint-1542058442637.jar:1.0.0-SNAPSHOT]
2018-11-18 12:15:18.661 [main] ERROR io.gomint.server.network.PlayerConnection - Could not deserialize / handle packet
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 10

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Windows
 - OS: [e.g. iOS8.1] 10

**Comment by ghost** [comment]
When are you going to realize that other peoples, not speaking German, read this too? Stop writing in German, please.

**Comment by LucGamesYT** [comment]
I'm not good at English and just not at describing. But you are welcome to translate it for me.

**Comment by ghost** [comment]
I'm not going to play translator for you the whole time. Use, because it serves the purpose, Deepl or Google Translate, for Christ's sake.

**Comment by TheAmyChan98** [comment]
Dann lass es sein. geNAZt kann es ja lesen und fertig.
Als nächstes soll ich noch ein issues im DIscord auf Englisch schreiben oder was ?
