### ISSUE TITLE
Shears error

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#430]
```
15:00:55.735 [main] ERROR io.gomint.server.network.PlayerConnection - Could not deserialize / handle packet
 java.lang.ClassCastException: io.gomint.server.inventory.item.ItemShears cannot be cast to io.gomint.inventory.item.ItemReduceBreaktime
        at io.gomint.server.world.block.Block.getFinalBreakTime(Block.java:676) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.handler.PacketPlayerActionHandler.handleBreakStart(PacketPlayerActionHandler.java:246) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.handler.PacketPlayerActionHandler.handle(PacketPlayerActionHandler.java:100) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.handler.PacketPlayerActionHandler.handle(PacketPlayerActionHandler.java:17) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handlePacket(PlayerConnection.java:755) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handleBufferData(PlayerConnection.java:696) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:601) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.updateNetwork(PlayerConnection.java:493) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:316) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:210) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:498) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:117) [GoMint.jar:1.0.0-SNAPSHOT]
```

**Comment by ghost** [comment]
Turns out that `io.gomint.server.inventory.item.ItemShears` is not implementing/extending the interface `io.gomint.inventory.item.ItemReduceBreaktime`. Clearly a bug. (@Janmm14 cleared that up)

**Comment by ghost** [comment]
I tried to fix it but it seems like there's something broken with the calculation what the break time is.
I implemented shears break time for wool and any other blocks. When I tried to break a leave block with shears it gave me that warning about incorrect break times. Break time was 50-100 and it should be 233. Weird. It worked for wool blocks but anything else did not
