### ISSUE TITLE
/op don't work

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#434]
21:10:39.860 [main] WARN  io.gomint.server.command.CommandManager - Command 'op' failed
 java.lang.NullPointerException: null
        at io.gomint.server.command.vanilla.OpCommand.execute(OpCommand.java:29) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.command.CommandManager.tryCommandDispatch(CommandManager.java:224) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.command.CommandManager.dispatchCommand(CommandManager.java:215) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.command.CommandManager.executeSystem(CommandManager.java:88) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:485) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:117) [GoMint.jar:1.0.0-SNAPSHOT]
21:10:39.861 [main] INFO  Command 'op' - Command has thrown an error. Please check the logs
GoMint> op
21:10:40.880 [main] WARN  io.gomint.server.command.CommandManager - Command 'op' failed
 java.lang.NullPointerException: null
        at io.gomint.server.command.vanilla.OpCommand.execute(OpCommand.java:29) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.command.CommandManager.tryCommandDispatch(CommandManager.java:224) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.command.CommandManager.dispatchCommand(CommandManager.java:215) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.command.CommandManager.executeSystem(CommandManager.java:88) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:485) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:117) [GoMint.jar:1.0.0-SNAPSHOT]
21:10:40.882 [main] INFO  Command 'op' - Command has thrown an error. Please check the logs
GoMint> op test
21:10:45.455 [main] INFO  Command 'op test' - Command for input '/op test' could not be found
GoMint>

**Comment by Shad0wCore** [comment]
There's a plugin created for op rights. This plugin was created by @janmm14 and listed in the plugins channel on the Discord. Closed.

**Comment by ghost** [comment]
that doesn't change the fact that /op on gomint don't work

**Comment by Janmm14** [comment]
Error happenend because you did not specified a player.

**Comment by ghost** [comment]
i did

**Comment by ghost** [comment]
GoMint> op twix meister
16:30:09.485 [main] INFO  Command 'op twix meister' - Command for input '/op twix meister' could not be found this gave me when i specified a player which is me and im online

**Comment by ghost** [comment]
are names with spaces not supported?

**Comment by Janmm14** [comment]
@captainleviftw I think you need `"` around names with spaces for it to work.

**Comment by ghost** [comment]
i added " and it said im now opped but it didnt gave me permissions

**Comment by Janmm14** [comment]
Yes, currently being op does not grant permissions.
