### ISSUE TITLE
Furnace Crash

### ISSUE THREAD

**Issue by voltexde** [gomint/gomint#443]
```

08:43:48.505 [main] ERROR io.gomint.server.Bootstrap - GoMint crashed:
 java.lang.NullPointerException: null
        at io.gomint.server.world.block.state.BlockfaceBlockState.data(BlockfaceBlockState.java:78) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.block.state.BlockState.toData(BlockState.java:98) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.block.Block.calculateBlockData(Block.java:286) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.block.Block.updateBlock(Block.java:264) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.block.Block.setBlockId(Block.java:810) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.block.Furnace.setBurning(Furnace.java:101) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.entity.tileentity.FurnaceTileEntity.update(FurnaceTileEntity.java:134) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.ChunkAdapter.tickTiles(ChunkAdapter.java:730) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldAdapter.tickChunks(WorldAdapter.java:541) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldAdapter.update(WorldAdapter.java:481) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldManager.update(WorldManager.java:62) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:501) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:120) [GoMint.jar:1.0.0-SNAPSHOT]
GoMint>

```

**Comment by ghost** [comment]
Alright. Basically, I got the same exception. Not on load up but when you interact with the furnace. Furthermore, when the smelting process starts.
![image](https://user-images.githubusercontent.com/17110757/49505549-4ad66d80-f87c-11e8-968f-81e367cb0d00.png)

**Comment by ghost** [comment]
Ok, turns out this only occurs when the smelting process starts for the first time. Afterwards this exception does not pop up again. Even more weird, GoMint crashes at the first smelting process. Any following smelting process does not crash GoMint.
