### ISSUE TITLE
Player null disconnected

### ISSUE THREAD

**Issue by voltexde** [gomint/gomint#457]
ProxProx

```
java.lang.NullPointerException
        at io.gomint.proxprox.network.DownstreamConnection.send(DownstreamConnection.java:733) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.handlePacket(UpstreamConnection.java:402) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.updateIncoming(UpstreamConnection.java:785) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.SocketEventListener.update(SocketEventListener.java:117) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.ProxProxProxy.<init>(ProxProxProxy.java:199) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_181]
        at io.gomint.proxprox.Bootstrap.main(Bootstrap.java:68) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
12:45:20.096 [main] ERROR io.gomint.proxprox.ProxProxProxy - Exception in main run
java.lang.NullPointerException
        at io.gomint.proxprox.network.DownstreamConnection.send(DownstreamConnection.java:733) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.handlePacket(UpstreamConnection.java:402) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.updateIncoming(UpstreamConnection.java:785) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.SocketEventListener.update(SocketEventListener.java:117) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.ProxProxProxy.<init>(ProxProxProxy.java:199) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_181]
        at io.gomint.proxprox.Bootstrap.main(Bootstrap.java:68) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
12:45:20.138 [main] ERROR io.gomint.proxprox.ProxProxProxy - Exception in main run
java.lang.NullPointerException
        at io.gomint.proxprox.network.DownstreamConnection.send(DownstreamConnection.java:733) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.handlePacket(UpstreamConnection.java:402) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.updateIncoming(UpstreamConnection.java:785) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.SocketEventListener.update(SocketEventListener.java:117) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.ProxProxProxy.<init>(ProxProxProxy.java:199) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_181]
        at io.gomint.proxprox.Bootstrap.main(Bootstrap.java:68) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
12:45:20.199 [main] ERROR io.gomint.proxprox.ProxProxProxy - Exception in main run
java.lang.NullPointerException
        at io.gomint.proxprox.network.DownstreamConnection.send(DownstreamConnection.java:733) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.handlePacket(UpstreamConnection.java:402) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.updateIncoming(UpstreamConnection.java:785) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.SocketEventListener.update(SocketEventListener.java:117) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.ProxProxProxy.<init>(ProxProxProxy.java:199) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_181]
        at io.gomint.proxprox.Bootstrap.main(Bootstrap.java:68) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
12:45:20.289 [main] ERROR io.gomint.proxprox.ProxProxProxy - Exception in main run
java.lang.NullPointerException
        at io.gomint.proxprox.network.DownstreamConnection.send(DownstreamConnection.java:733) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.handlePacket(UpstreamConnection.java:402) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.UpstreamConnection.updateIncoming(UpstreamConnection.java:785) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.network.SocketEventListener.update(SocketEventListener.java:117) ~[ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at io.gomint.proxprox.ProxProxProxy.<init>(ProxProxProxy.java:199) [ProxProx.jar:1.0-SNAPSHOT-"fe3a1ff"]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_181]
```

GoMint

```
12:47:48.565 [TCP Threads] DEBUG io.gomint.server.plugin.SimplePluginManager - Calling event PlayerPreLoginEvent(clientAddress=/127.0.0.1:56236)
12:47:48.567 [TCP Threads] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'network.newConnection.raknet'
12:47:48.568 [TCP Threads] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'network.newConnection.tcp'
12:47:48.580 [main] DEBUG io.gomint.server.network.NetworkManager - Adding new connection to the server: unknown
12:47:48.580 [main] INFO  io.gomint.server.network.PlayerConnection - Player null disconnected
```

**Comment by ghost** [comment]
This issue is a 1:1 duplicate of the issue #52 in the ProxProx repository.

**Comment by Janmm14** [comment]
https://github.com/gomint/proxprox/issues/52
