### ISSUE TITLE
error when using mcpc worlds

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#462]
im using this world
https://sellfy.com/p/VgDG/
i start server
i get this error 
```
2018-12-09 12:54:07.778 [main] INFO  io.gomint.server.Bootstrap - Loading lib: C:\Users\arjxy\Desktop\gomint\libs\mysql-connector-java-8.0.11.jar
2018-12-09 12:54:09.100 [main] INFO  io.gomint.server.GoMintServer - Starting GoMint 1.0.0 (MC:PE 1.7.0) - s:fe00f88-b:master
2018-12-09 12:54:09.101 [main] INFO  io.gomint.server.GoMintServer - Loading block, item and entity registers
2018-12-09 12:54:10.013 [main] INFO  io.gomint.server.GoMintServer - Loading assets library...
2018-12-09 12:54:10.102 [main] INFO  io.gomint.server.assets.AssetsLibrary - Loaded 577 shapeless, 416 shaped and 75 smelting recipes
2018-12-09 12:54:10.234 [main] INFO  io.gomint.server.assets.AssetsLibrary - Loaded 1038 items into creative inventory
2018-12-09 12:54:10.557 [main] INFO  io.gomint.server.GoMintServer - Initializing recipes...
2018-12-09 12:54:10.564 [main] INFO  io.gomint.server.world.WorldManager - Attempting to load world 'world'
2018-12-09 12:54:10.566 [main] INFO  io.gomint.server.world.WorldManager - Detected leveldb world 'world'
2018-12-09 12:54:10.665 [main] ERROR io.gomint.server.world.WorldManager - Could not create new world
io.gomint.server.world.WorldCreateException: Folder with name 'world' already exists
	at io.gomint.server.world.leveldb.LevelDBWorldAdapter.create(LevelDBWorldAdapter.java:150) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.WorldManager.createWorld(WorldManager.java:230) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:412) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.Bootstrap.main(Bootstrap.java:120) [GoMint.jar:1.0.0-SNAPSHOT]
2018-12-09 12:54:10.672 [main] ERROR io.gomint.server.GoMintServer - Failed to load or generate default world
io.gomint.server.world.WorldLoadException: Missing level.dat
	at io.gomint.server.world.leveldb.LevelDBWorldAdapter.loadLevelDat(LevelDBWorldAdapter.java:316) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.leveldb.LevelDBWorldAdapter.<init>(LevelDBWorldAdapter.java:113) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.leveldb.LevelDBWorldAdapter.load(LevelDBWorldAdapter.java:224) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.WorldManager.loadLevelDBWorld(WorldManager.java:180) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.world.WorldManager.loadWorld(WorldManager.java:133) ~[GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:386) [GoMint.jar:1.0.0-SNAPSHOT]
	at io.gomint.server.Bootstrap.main(Bootstrap.java:120) [GoMint.jar:1.0.0-SNAPSHOT]
2018-12-09 12:54:10.677 [main] INFO  io.gomint.server.GoMintServer - Starting shutdown...
2018-12-09 12:54:10.841 [main] INFO  io.gomint.server.GoMintServer - Shutdown completed
```

**Comment by Janmm14** [comment]
I suggest trying to load it with a minecraft 1.8 server first, maybe it can create the level.dat file for gomint and then copy the level.dat file to gomint

**Comment by ghost** [comment]
Aight, what's the status on this issue?

**Comment by ghost** [comment]
Closed due no response.
