### ISSUE TITLE
OakTree.grow throws error

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#470]
OakTree.grow() don't work and throws error but BirchTree.grow() don't throw error and works

**Comment by Janmm14** [comment]
what error?
... do i really need to ask this?

**Comment by ghost** [comment]
i thought i pasted pastebin link here.. wait lol

**Comment by ghost** [comment]
```
16:45:11.730 [main] INFO  io.gomint.World-u - Loaded 81 chunks in 197 ms
16:45:11.994 [main] WARN  io.gomint.server.command.CommandManager - Command 'plot create' failed
 java.lang.NullPointerException: null
        at io.gomint.server.world.BlockRuntimeIDs.lookup(BlockRuntimeIDs.java:101) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.BlockRuntimeIDs.from(BlockRuntimeIDs.java:81) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.ChunkSlice.setBlock(ChunkSlice.java:170) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.ChunkAdapter.setBlock(ChunkAdapter.java:392) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldAdapter.setBlock(WorldAdapter.java:378) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.block.Block.copyFromBlock(Block.java:499) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.world.generator.object.Tree.placeObject(Tree.java:87) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.world.generator.object.OakTree.grow(OakTree.java:31) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at levi.gomint.plot.PlotCommand.execute(PlotCommand.java:74) ~[?:?]
        at io.gomint.server.command.CommandManager.tryCommandDispatch(CommandManager.java:224) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.command.CommandManager.dispatchCommand(CommandManager.java:210) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.entity.EntityPlayer.dispatchCommand(EntityPlayer.java:1683) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.handler.PacketCommandRequestHandler.handle(PacketCommandRequestHandler.java:26) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.handler.PacketCommandRequestHandler.handle(PacketCommandRequestHandler.java:17) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handlePacket(PlayerConnection.java:756) [GoMint.jar:1.0.0-SNAPSHOT]        at io.gomint.server.network.PlayerConnection.handleBufferData(PlayerConnection.java:697) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:602) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.updateNetwork(PlayerConnection.java:494) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:317) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:210) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:498) [GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:120) [GoMint.jar:1.0.0-SNAPSHOT]
16:45:12.143 [main] WARN  io.gomint.server.GoMintServer - Running behind: 1.4064697109074233 / 20.0 tps
16:45:14.935 [main] WARN  io.gomint.server.GoMintServer - Running behind: 12.658227265521043 / 20.0 tps
16:45:23.809 [main] WARN  io.gomint.server.GoMintServer - Running behind: 14.925372762546221 / 20.0 tps
16:45:24.473 [jRaknet Ticker] WARN  io.gomint.server.network.NetworkManager - Packet loss detected: 66.667% | Resend queue: 1 | ACK: 2 | NAK: 4 | RTT: 17
```

**Comment by ghost** [comment]
I'd reckon to take a look at the two last stack trace elements. As far as I can tell, I don't think this has anything to do with the `OakTree#grow()` call. The thrown exception is similar to the exception which is repeated over and over again as described in #468.
