### ISSUE TITLE
GoMint fails upon attempt converting/reading an world with Anvil format

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#478]
**Describe the bug**
I loaded and pasted a schematic file to my void mc java world and then i put it on my gomint server as default world but it crash
**To Reproduce**
1. Put a mc java world to gomint
2. Use it as default world
3. Start server

**Expected behavior**
Should be able to load the mc java world no problem
**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Version 10

**Smartphone (please complete the following information):**

**Additional context**
```
20:03:32.339 [main] INFO  io.gomint.server.GoMintServer - Initializing recipes...
20:03:32.342 [main] INFO  io.gomint.server.world.WorldManager - Attempting to load world 'world'
20:03:32.345 [main] INFO  io.gomint.server.world.WorldManager - Detected anvil world 'world', converting...
20:03:32.523 [main] ERROR io.gomint.server.Bootstrap - GoMint crashed:
 java.lang.NullPointerException: null
        at io.gomint.server.world.converter.anvil.BlockConverter.<init>(BlockConverter.java:23) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.converter.anvil.AnvilConverter.<init>(AnvilConverter.java:129) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldManager.convertAndLoad(WorldManager.java:164) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.world.WorldManager.loadWorld(WorldManager.java:140) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.GoMintServer.startAfterRegistryInit(GoMintServer.java:386) ~[GoMint.jar:1.0.0-SNAPSHOT]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:120) [GoMint.jar:1.0.0-SNAPSHOT]
GoMint>
```

**Comment by Janmm14** [comment]
anvil world conversion

**Comment by rdstonech** [comment]
I have the same error when I tried to convert Anvil world (world is valid, I can open it on pmmp).
It affects all my Anvil worlds.

OS: Windows 10

I can give a world, if it's needed

**Comment by DelxHQ** [comment]
@rdstonech PMMP isn't anvil, it uses its own custom version of anvil.

**Comment by rdstonech** [comment]
@DelxHQ This world created **not by pmmp**, it's created in Java Edition and have **mca** format. I said that the world is valid and you can enter it

**Comment by geNAZt** [comment]
Fixed in latest commit
