### ISSUE TITLE
Crafting Error

### ISSUE THREAD

**Issue by Ali1v** [gomint/gomint#567]
If you want to craft an item it wont work

Error code:

NullPointerException: None
    at io.gomint.server.crafting.CraftingRecipe.canBeUsedForCrafting(CraftingRecipe.java:59)
    at io.gomint.server.crafting.ShapedRecipe.isCraftable(ShapedRecipe.java:188)
    at io.gomint.server.network.handler.PacketCraftingEventHandler.handle(PacketCraftingEventHandler.java:63)
    at io.gomint.server.network.handler.PacketCraftingEventHandler.handle(PacketCraftingEventHandler.java:26)
    at io.gomint.server.network.PlayerConnection.handlePacket(PlayerConnection.java:610)

**Comment by geNAZt** [comment]
Fixed
