### ISSUE TITLE
Elytra Bug

### ISSUE THREAD

**Issue by KCodeYT** [gomint/gomint#57]
GoMint> Unknown action id: 16
23:10:46.615 [main] ERROR io.gomint.server.network.PlayerConnection - Error whilst processing packet:
 java.lang.NullPointerException: null
        at io.gomint.server.network.handler.PacketPlayerActionHandler.handle(PacketPlayerActionHandler.java:25) ~[GoMint.jar:?]
        at io.gomint.server.network.handler.PacketPlayerActionHandler.handle(PacketPlayerActionHandler.java:19) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handlePacket(PlayerConnection.java:534) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:463) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handleBatchPacket(PlayerConnection.java:514) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:451) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.updateNetwork(PlayerConnection.java:269) [GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:177) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager$1.accept(NetworkManager.java:76) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager$1.accept(NetworkManager.java:73) [GoMint.jar:?]
        at io.gomint.server.util.collection.KolobokePlayerConnectionMap.forEach(KolobokePlayerConnectionMap.java:179) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:199) [GoMint.jar:?]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:307) [GoMint.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_152]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_152]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_152]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:98) [GoMint.jar:?]

Wenn ich mit einer Elytra lande oder versuche zu fliegen.

**Comment by geNAZt** [comment]
Fixed long time ago
