### ISSUE TITLE
Crash upon server start

### ISSUE THREAD

**Issue by IkeVoodoo** [GoMint/GoMint#764]
**Describe the bug**
Whenever the GoMint server starts I get the following text:
`13:58:25.190 [main] INFO  io.gomint.server.GoMintServer - Starting GoMint 1.0.0 (MC:BE 1.16.200 [422]) - s:012d2f05
13:58:25.194 [GoMint Main Thread] INFO  io.gomint.server.GoMintServer - Loading block, item and entity registers
13:58:25.344 [GoMint Main Thread] ERROR io.gomint.server.Bootstrap - GoMint crashed:
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[?:?]
        at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:438) ~[?:?]
        at java.io.File.getCanonicalPath(File.java:620) ~[?:?]
        at java.io.File.getCanonicalFile(File.java:645) ~[?:?]
        at io.gomint.server.util.ClassPath.scan(ClassPath.java:64) ~[GoMint.jar:?]
        at io.gomint.server.util.ClassPath.<init>(ClassPath.java:59) ~[GoMint.jar:?]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:215) ~[GoMint.jar:?]
        at io.gomint.server.Bootstrap.bootstrap(Bootstrap.java:72) ~[GoMint.jar:?]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:42) [GoMint.jar:?]`

**To Reproduce**
1. Download GoMint on windows
2. Start GoMint

**Expected behavior**
The server should have started up and a command-line should've been shown

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows
 - Version  10

**Smartphone (please complete the following information):**
None

**Additional context**
No additional context

**Comment by Janmm14** [comment]
Project abandoned
