### ISSUE TITLE
Unknown command execution causes AIOBE

### ISSUE THREAD

**Issue by Janmm14** [gomint/gomint#92]
```
21:06:08.531 [main] DEBUG io.gomint.server.network.PlayerConnection - Packet: PacketCommandRequest(inputCommand=/lhihgiorhgir, commandOrigin=CommandOrigin(unknown1=0, uuid=8d85231a-c13a-4be0-9c85-195f5db450d1, unknown2=0, type=0))
21:06:08.532 [main] ERROR io.gomint.server.network.PlayerConnection - Error whilst processing packet:
 java.lang.ArrayIndexOutOfBoundsException: 1
        at io.gomint.server.network.handler.PacketCommandRequestHandler.handle(PacketCommandRequestHandler.java:47) ~[GoMint.jar:?]
        at io.gomint.server.network.handler.PacketCommandRequestHandler.handle(PacketCommandRequestHandler.java:21) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handlePacket(PlayerConnection.java:550) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handleBufferData(PlayerConnection.java:499) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.handleSocketData(PlayerConnection.java:423) ~[GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.updateNetwork(PlayerConnection.java:293) [GoMint.jar:?]
        at io.gomint.server.network.PlayerConnection.update(PlayerConnection.java:201) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager$1.accept(NetworkManager.java:75) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager$1.accept(NetworkManager.java:72) [GoMint.jar:?]
        at io.gomint.server.util.collection.KolobokePlayerConnectionMap.forEach(KolobokePlayerConnectionMap.java:179) [GoMint.jar:?]
        at io.gomint.server.network.NetworkManager.update(NetworkManager.java:197) [GoMint.jar:?]
        at io.gomint.server.GoMintServer.<init>(GoMintServer.java:306) [GoMint.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_162]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_162]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_162]
        at io.gomint.server.Bootstrap.main(Bootstrap.java:103) [GoMint.jar:?]
```

**Comment by geNAZt** [comment]
Fixed in https://github.com/GoMint/GoMint/commit/7122d2ba50270e57f27b8d03ad51d624fed80c0a
